//! Canonical test vectors for Gate 3 — CBOR and signature golden values.
//!
//! These vectors pin the exact byte output of the canonical CBOR encoder and the
//! Ed25519 signer for a fixed, deterministic input. Any change to the encoding,
//! the domain separator, the field ordering, or the signing algorithm that
//! alters these bytes is a **breaking protocol change** and requires:
//!
//! 1. An ADR update (ADR-008 for CBOR, ADR-002 for crypto)
//! 2. Change-control review (`.agent/CHANGE_CONTROL.md`)
//! 3. Update to ALL dependent test vectors and simulation data
//!
//! # Vector input
//!
//! All inputs are fully deterministic:
//! - UUIDs: fixed byte sequences
//! - Nonce: `[0x01; 16]`
//! - Timestamps: fixed integers
//! - Amount: 150 (INR paise = ₹1.50)
//! - Counter: 1
//! - Signing key: `Ed25519TestSigner::from_seed([0x42; 32])`
//!
//! # How to update vectors
//!
//! 1. Run with `REGENERATE_VECTORS=1 cargo test test_vectors -- --nocapture`
//! 2. Copy the printed hex values into the expected constants below
//! 3. Confirm the change through change-control before committing
//!
//! This file deliberately does NOT auto-update — the freeze is intentional.

use resilientpay_core::{
    crypto::{sign_envelope, Ed25519TestSigner, Signer},
    envelope::EnvelopeBuilder,
    money::Money,
    serialization::{encode_envelope_cbor, signing_input},
    types::{CredentialId, KeyId, MerchantId, TransactionId},
    PROTOCOL_VERSION,
};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Fixed vector inputs (all deterministic)
// ---------------------------------------------------------------------------

const VECTOR_TX_UUID: &str = "00000000-0000-0000-0000-000000000001";
const VECTOR_CR_UUID: &str = "00000000-0000-0000-0000-000000000002";
const VECTOR_KEY_UUID: &str = "00000000-0000-0000-0000-000000000003";
const VECTOR_MER_UUID: &str = "00000000-0000-0000-0000-000000000004";
const VECTOR_NONCE: [u8; 16] = [0x01u8; 16];
const VECTOR_AMOUNT: u64 = 150; // 150 paise = ₹1.50
const VECTOR_COUNTER: u64 = 1;
const VECTOR_CREATED: i64 = 1_700_000_000;
const VECTOR_EXPIRES: i64 = 1_700_003_600;
const VECTOR_SEED: [u8; 32] = [0x42u8; 32];

fn vector_envelope() -> resilientpay_core::PaymentEnvelopeCore {
    EnvelopeBuilder::new()
        .protocol_version(PROTOCOL_VERSION)
        .tx_id(TransactionId::from_uuid(
            Uuid::parse_str(VECTOR_TX_UUID).unwrap(),
        ))
        .credential_id(CredentialId::from_uuid(
            Uuid::parse_str(VECTOR_CR_UUID).unwrap(),
        ))
        .payer_key_id(KeyId::from_uuid(Uuid::parse_str(VECTOR_KEY_UUID).unwrap()))
        .merchant_id(MerchantId::from_uuid(
            Uuid::parse_str(VECTOR_MER_UUID).unwrap(),
        ))
        .amount(Money::new(VECTOR_AMOUNT, "INR").unwrap())
        .counter(VECTOR_COUNTER)
        .nonce(VECTOR_NONCE)
        .created_at_unix_secs(VECTOR_CREATED)
        .expires_at_unix_secs(VECTOR_EXPIRES)
        .build()
        .unwrap()
}

// ---------------------------------------------------------------------------
// Frozen expected values
//
// Generated by running:
//   cargo test test_vectors::generate -- --nocapture
// on commit b77d45a of the feat/sdk-serialization-crypto branch.
//
// Protocol: PROTOCOL_VERSION = 1
// CBOR: 13-element array, field order per PAYMENT_PROTOCOL.md §2
// Signing domain: b"resilientpay:payment-envelope:v1:"
// Signature: Ed25519 (ed25519-dalek 2.x), deterministic
// ---------------------------------------------------------------------------

// Pinned on: 2026-09-10, branch feat/sdk-integration-tests, parent commit b77d45a
// Protocol: PROTOCOL_VERSION = 1
// CBOR encoding: 13-element array, field order per PAYMENT_PROTOCOL.md §2
// Signing domain: b"resilientpay:payment-envelope:v1:"
// Signature scheme: Ed25519 (ed25519-dalek 2.x), deterministic
//
// ANY change to these bytes requires change-control review (ADR-008 / ADR-002).

const EXPECTED_CBOR_HEX: &str = "8d015000000000000000000000000000000001500000000000000000000000000000000250000000000000000000000000000000035000000000000000000000000000000004189663494e520150010101010101010101010101010101011a6553f1001a6553ff10f6f6";

const EXPECTED_CBOR_LEN: usize = 106; // bytes

const EXPECTED_PUBLIC_KEY_HEX: &str =
    "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12";

const EXPECTED_SIGNATURE_HEX: &str =
    "04bbdb205dd371101fb2ad439d5f1d38cfc9146f7edd157a22f3476c42b0112359c46f1f0ea16aa1300cff1576628264bcb2f33b1d4ac2d6d8f592e16406ee07";

// Convenience: min length checks retained for readability
const EXPECTED_CBOR_MIN_LEN: usize = EXPECTED_CBOR_LEN;
const EXPECTED_SIGNING_INPUT_MIN_LEN: usize = 33 /* domain sep */ + EXPECTED_CBOR_MIN_LEN;

fn decode_hex(hex: &str) -> Vec<u8> {
    // Strip interior whitespace / backslash-continuations introduced by string literals
    let clean: String = hex
        .chars()
        .filter(|c| !c.is_whitespace() && *c != '\\')
        .collect();
    (0..clean.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&clean[i..i + 2], 16).expect("valid hex"))
        .collect()
}

// ---------------------------------------------------------------------------
// Vector tests — structural checks (Gate 3 phase 1)
// ---------------------------------------------------------------------------

#[test]
fn vector_cbor_encodes_to_nonzero_bytes() {
    let env = vector_envelope();
    let bytes = encode_envelope_cbor(&env).unwrap();
    assert!(!bytes.is_empty());
    assert!(
        bytes.len() >= EXPECTED_CBOR_MIN_LEN,
        "CBOR too short: {} bytes (expected >= {})",
        bytes.len(),
        EXPECTED_CBOR_MIN_LEN
    );
}

#[test]
fn vector_signing_input_starts_with_domain_separator() {
    use resilientpay_core::serialization::SIGNING_DOMAIN_SEPARATOR;
    let env = vector_envelope();
    let input = signing_input(&env).unwrap();
    assert!(input.starts_with(SIGNING_DOMAIN_SEPARATOR));
    assert!(input.len() >= EXPECTED_SIGNING_INPUT_MIN_LEN);
}

#[test]
fn vector_cbor_is_deterministic_across_runs() {
    let env = vector_envelope();
    let b1 = encode_envelope_cbor(&env).unwrap();
    let b2 = encode_envelope_cbor(&env).unwrap();
    let b3 = encode_envelope_cbor(&env).unwrap();
    assert_eq!(b1, b2);
    assert_eq!(b2, b3);
}

#[test]
fn vector_signature_is_deterministic() {
    let signer = Ed25519TestSigner::from_seed(&VECTOR_SEED);
    let env = vector_envelope();
    let s1 = sign_envelope(&env, &signer).unwrap();
    let s2 = sign_envelope(&env, &signer).unwrap();
    assert_eq!(
        s1.to_bytes(),
        s2.to_bytes(),
        "Ed25519 must be deterministic"
    );
}

#[test]
fn vector_signature_length() {
    let signer = Ed25519TestSigner::from_seed(&VECTOR_SEED);
    let env = vector_envelope();
    let sig = sign_envelope(&env, &signer).unwrap();
    assert_eq!(
        sig.to_bytes().len(),
        64,
        "Ed25519 signature must be 64 bytes"
    );
}

#[test]
fn vector_signature_verifies_with_corresponding_public_key() {
    let signer = Ed25519TestSigner::from_seed(&VECTOR_SEED);
    let env = vector_envelope();
    let sig = sign_envelope(&env, &signer).unwrap();
    let verifier = signer.verifier();
    resilientpay_core::verify_envelope(&env, &sig, &verifier).unwrap();
}

/// Print all vector values for inspection and future pinning.
/// Run with: cargo test generate_and_print_vectors -- --nocapture
#[test]
fn generate_and_print_vectors() {
    use resilientpay_core::serialization::SIGNING_DOMAIN_SEPARATOR;

    let signer = Ed25519TestSigner::from_seed(&VECTOR_SEED);
    let env = vector_envelope();

    let cbor_bytes = encode_envelope_cbor(&env).unwrap();
    let signing_bytes = signing_input(&env).unwrap();
    let sig = sign_envelope(&env, &signer).unwrap();
    let pub_key = signer.public_key().to_bytes();

    let to_hex = |b: &[u8]| b.iter().map(|x| format!("{x:02x}")).collect::<String>();

    println!("\n=== ResilientPay Protocol Test Vectors (Gate 3) ===");
    println!("Protocol version : {PROTOCOL_VERSION}");
    println!("TX UUID          : {VECTOR_TX_UUID}");
    println!("CR UUID          : {VECTOR_CR_UUID}");
    println!("Key UUID         : {VECTOR_KEY_UUID}");
    println!("Merchant UUID    : {VECTOR_MER_UUID}");
    println!("Nonce            : {}", to_hex(&VECTOR_NONCE));
    println!("Amount (paise)   : {VECTOR_AMOUNT}");
    println!("Currency         : INR");
    println!("Counter          : {VECTOR_COUNTER}");
    println!("Created          : {VECTOR_CREATED}");
    println!("Expires          : {VECTOR_EXPIRES}");
    println!("Signing seed     : {}", to_hex(&VECTOR_SEED));
    println!("---");
    println!(
        "Domain separator : {}",
        std::str::from_utf8(SIGNING_DOMAIN_SEPARATOR).unwrap()
    );
    println!(
        "CBOR bytes ({:>3}B): {}",
        cbor_bytes.len(),
        to_hex(&cbor_bytes)
    );
    println!(
        "Signing input ({:>3}B): {}",
        signing_bytes.len(),
        to_hex(&signing_bytes)
    );
    println!("Public key (hex) : {}", to_hex(&pub_key));
    println!("Signature (hex)  : {}", to_hex(&sig.to_bytes()));
    println!("=== end vectors ===\n");
}

// ---------------------------------------------------------------------------
// Exact-byte pinning tests (Gate 3 freeze)
//
// These tests compare actual encoder/signer output against the frozen hex
// constants above. A failure here means the encoding or signing algorithm
// has changed — which is a breaking protocol change.
// ---------------------------------------------------------------------------

#[test]
fn pinned_cbor_bytes_match_frozen_vector() {
    let env = vector_envelope();
    let actual = encode_envelope_cbor(&env).unwrap();
    let expected = decode_hex(EXPECTED_CBOR_HEX);

    assert_eq!(
        actual.len(),
        EXPECTED_CBOR_LEN,
        "CBOR byte length changed: expected {EXPECTED_CBOR_LEN}, got {}",
        actual.len()
    );
    assert_eq!(
        actual,
        expected,
        "CBOR bytes changed — this is a breaking protocol change requiring ADR-008 update.\n\
         Expected: {EXPECTED_CBOR_HEX}\n\
         Actual:   {}",
        actual
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );
}

#[test]
fn pinned_public_key_matches_frozen_vector() {
    let signer = Ed25519TestSigner::from_seed(&VECTOR_SEED);
    let actual_bytes = signer.public_key().to_bytes();
    let expected_bytes = decode_hex(EXPECTED_PUBLIC_KEY_HEX);

    assert_eq!(
        actual_bytes.as_slice(),
        expected_bytes.as_slice(),
        "Public key changed — signing key derivation is different from the frozen vector.\n\
         Expected: {EXPECTED_PUBLIC_KEY_HEX}\n\
         Actual:   {}",
        actual_bytes
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );
}

#[test]
fn pinned_signature_matches_frozen_vector() {
    let signer = Ed25519TestSigner::from_seed(&VECTOR_SEED);
    let env = vector_envelope();
    let sig = sign_envelope(&env, &signer).unwrap();
    let actual_bytes = sig.to_bytes();
    let expected_bytes = decode_hex(EXPECTED_SIGNATURE_HEX);

    assert_eq!(
        actual_bytes.as_slice(),
        expected_bytes.as_slice(),
        "Signature changed — encoding, domain separator, or signing changed from frozen vector.\n\
         This is a breaking protocol change requiring ADR-008 / ADR-002 update.\n\
         Expected: {EXPECTED_SIGNATURE_HEX}\n\
         Actual:   {}",
        actual_bytes
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );
}
