//! Hardware-backed Key Management Abstraction.
//!
//! This module defines the boundaries for the SDK to interact with external,
//! hardware-backed keystores (e.g., Android Keystore, iOS Secure Enclave).
//!
//! # Security Property
//! Private key material MUST NEVER cross this boundary into the Rust SDK memory.
//! The `KeyManager` trait issues abstract `Signer` implementations that delegate
//! the actual cryptographic operations back to the secure hardware.

use crate::crypto::{CryptoError, PublicKey, Signer, Verifier};
use crate::types::KeyId;

/// A secure facility for generating, storing, and utilizing asymmetric keys.
///
/// In a production environment, this is implemented over FFI/JNI to route
/// calls into the mobile OS's hardware keystore APIs.
pub trait KeyManager {
    /// Generates a new hardware-backed keypair.
    ///
    /// Returns the unique `KeyId` generated by the hardware store, and the
    /// public portion of the key. The private key remains in hardware.
    fn generate_key(&self) -> Result<(KeyId, PublicKey), CryptoError>;

    /// Retrieves an abstract `Signer` for the given key identity.
    ///
    /// The returned signer delegates cryptographic operations to the hardware.
    fn get_signer(&self, key_id: &KeyId) -> Result<Box<dyn Signer>, CryptoError>;

    /// Retrieves an abstract `Verifier` for the given key identity.
    fn get_verifier(&self, key_id: &KeyId) -> Result<Box<dyn Verifier>, CryptoError>;
}

/// A purely in-memory KeyManager for testing purposes.
///
/// **WARNING:** Do not use in production. Keys are stored in standard RAM.
#[cfg(test)]
pub mod testing {
    use super::*;
    use crate::crypto::Ed25519TestSigner;
    use rand::{thread_rng, RngCore};
    use std::collections::HashMap;
    use std::sync::{Arc, Mutex};

    #[derive(Default, Clone)]
    pub struct TestKeyManager {
        seeds: Arc<Mutex<HashMap<KeyId, [u8; 32]>>>,
    }

    impl TestKeyManager {
        pub fn new() -> Self {
            Self {
                seeds: Arc::new(Mutex::new(HashMap::new())),
            }
        }
    }

    impl KeyManager for TestKeyManager {
        fn generate_key(&self) -> Result<(KeyId, PublicKey), CryptoError> {
            let mut seed = [0u8; 32];
            thread_rng().fill_bytes(&mut seed);

            let signer = Ed25519TestSigner::from_seed(&seed);
            let key_id = KeyId::generate();
            let pk = signer.public_key().clone();

            self.seeds.lock().unwrap().insert(key_id, seed);

            Ok((key_id, pk))
        }

        fn get_signer(&self, key_id: &KeyId) -> Result<Box<dyn Signer>, CryptoError> {
            let map = self.seeds.lock().unwrap();
            if let Some(seed) = map.get(key_id) {
                Ok(Box::new(Ed25519TestSigner::from_seed(seed)))
            } else {
                Err(CryptoError::MalformedInput {
                    reason: "Key not found".into(),
                })
            }
        }

        fn get_verifier(&self, key_id: &KeyId) -> Result<Box<dyn Verifier>, CryptoError> {
            let map = self.seeds.lock().unwrap();
            if let Some(seed) = map.get(key_id) {
                let signer = Ed25519TestSigner::from_seed(seed);
                Ok(Box::new(signer.verifier()))
            } else {
                Err(CryptoError::MalformedInput {
                    reason: "Key not found".into(),
                })
            }
        }
    }
}
